package tech.liujin.wuxio.jsonparserlib.json;

/**
 * @author Liujin 2019/4/18:13:19:42
 */
public class JSONString {

      public static final String TEMP = "{\n"
          + "    \"error\": false,\n"
          + "    \"results\": [\n"
          + "        {\n"
          + "            \"_id\": \"5c96259a9d21225de6278cd6\",\n"
          + "            \"createdAt\": \"2019-03-23T12:24:58.142Z\",\n"
          + "            \"desc\": \"一个可切换数据状态的布局，包含了加载布局，空数据布局，错误布局\",\n"
          + "            \"images\": [\n"
          + "                \"https://ww1.sinaimg.cn/large/0073sXn7gy1g25pmtf1g3g30k00zkhdt\"\n"
          + "            ],\n"
          + "            \"publishedAt\": \"2019-04-17T01:50:22.760Z\",\n"
          + "            \"source\": \"web\",\n"
          + "            \"type\": \"Android\",\n"
          + "            \"url\": \"https://github.com/F1ReKing/StatusLayout\",\n"
          + "            \"used\": true,\n"
          + "            \"who\": \"潇湘剑雨\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"_id\": \"5ca1e39a9d21225def25413d\",\n"
          + "            \"createdAt\": \"2019-04-01T10:10:34.674Z\",\n"
          + "            \"desc\": \"关于状态栏方案总结案例，适合于绝大多数的使用场景……\",\n"
          + "            \"publishedAt\": \"2019-04-17T01:49:40.411Z\",\n"
          + "            \"source\": \"web\",\n"
          + "            \"type\": \"Android\",\n"
          + "            \"url\": \"https://github.com/yangchong211/YCStatusBar\",\n"
          + "            \"used\": true,\n"
          + "            \"who\": \"潇湘剑雨\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"_id\": \"5cb3dfdb9d21220322355ecd\",\n"
          + "            \"createdAt\": \"2019-04-15T01:35:23.864Z\",\n"
          + "            \"desc\": \"Android 9.0中的新功能 - PrecomputedText\",\n"
          + "            \"publishedAt\": \"2019-04-16T01:28:58.839Z\",\n"
          + "            \"source\": \"web\",\n"
          + "            \"type\": \"Android\",\n"
          + "            \"url\": \"https://weilu.blog.csdn.net/article/details/89282221\",\n"
          + "            \"used\": true,\n"
          + "            \"who\": \"潇湘剑雨\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"_id\": \"5cac623a9d21220322355ec1\",\n"
          + "            \"createdAt\": \"2019-04-09T09:13:30.178Z\",\n"
          + "            \"desc\": \"阿里开源新一代混合技术方案 FlutterBoost\",\n"
          + "            \"publishedAt\": \"2019-04-09T09:14:09.156Z\",\n"
          + "            \"source\": \"web\",\n"
          + "            \"type\": \"Android\",\n"
          + "            \"url\": \"https://github.com/alibaba/flutter_boost\",\n"
          + "            \"used\": true,\n"
          + "            \"who\": \"潇湘剑雨\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"_id\": \"5caab6489d2122031c18f56d\",\n"
          + "            \"createdAt\": \"2019-04-08T02:47:36.321Z\",\n"
          + "            \"desc\": \"支持上拉加载更多，下拉刷新，可以自定义头部和底部，使用一个原生recyclerView就可以搞定复杂界面。支持自由切换状态【加载中，加载成功，加载失败，没网络等状态】的控件，可以自定义状态视图View。拓展功能【支持长按拖拽，侧滑删除】，轻量级 。已经用于多个实际项目中，持续更新……\",\n"
          + "            \"images\": [\n"
          + "                \"https://ww1.sinaimg.cn/large/0073sXn7gy1g1w6n01bt6j308c0go74r\"\n"
          + "            ],\n"
          + "            \"publishedAt\": \"2019-04-09T00:53:48.433Z\",\n"
          + "            \"source\": \"web\",\n"
          + "            \"type\": \"Android\",\n"
          + "            \"url\": \"https://github.com/yangchong211/YCRefreshView\",\n"
          + "            \"used\": true,\n"
          + "            \"who\": \"潇湘剑雨\"\n"
          + "        }\n"
          + "    ]\n"
          + "}";
}
