package com.example.wuxio.jsonparserlib.json;

/**
 * @author wuxio 2018-05-15:11:51
 */
public class TestJson {

      public static final String Json = "{\n"
          + "\t\"name\": \"菜鸟教程\",\n"
          + "\t\"int\": 12,\n"
          + "\t\"long\": 696969696,\n"
          + "\t\"double\": 1589.96,\n"
          + "\t\"boolean\": true,\n"
          + "\t\"empty\": null,\n"
          + "\t\"stringArray\": [\n"
          + "\t\t\"Hello\",\n"
          + "\t\t\"World\",\n"
          + "\t\t\"Json\"\n"
          + "\t],\n"
          + "\t\"intArray\": [\n"
          + "\t\t12, 24, 36\n"
          + "\t],\n"
          + "\t\"longArray\": [\n"
          + "\t\t11, 22, 33\n"
          + "\t],\n"
          + "\t\"doubleArray\": [\n"
          + "\t\t10.0, 11.1, 12.2\n"
          + "\t],\n"
          + "\t\"booleanArray\": [\n"
          + "\t\ttrue, false, true\n"
          + "\t],\n"
          + "\t\"object\": {\n"
          + "\t\t\"name\": \"wu xiong\",\n"
          + "\t\t\"age\": 27\n"
          + "\t},\n"
          + "\t\"objectArray\": [{\n"
          + "\t\t\t\"name\": \"sun\",\n"
          + "\t\t\t\"age\": 30\n"
          + "\t\t},\n"
          + "\t\t{\n"
          + "\t\t\t\"name\": \"liu\",\n"
          + "\t\t\t\"age\": 30\n"
          + "\t\t},\n"
          + "\t\t{\n"
          + "\t\t\t\"name\": \"wang\",\n"
          + "\t\t\t\"age\": 30\n"
          + "\t\t}\n"
          + "\t],\n"
          + "\t\"skipString\":\"skip to there\"\n"
          + "}";
}
